# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class DatacrawlerItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    ten = scrapy.Field()
    url_img = scrapy.Field()
    url_installment = scrapy.Field()
    gia = scrapy.Field()
    gia_online = scrapy.Field()
    gia_cu = scrapy.Field()
    khuyen_mai = scrapy.Field()
    mau_sac = scrapy.Field()
    cong_nghe_man_hinh = scrapy.Field()
    do_phan_giai = scrapy.Field()
    mau_man_hinh = scrapy.Field()
    chuan_man_hinh = scrapy.Field()
    cong_nghe_cam_ung = scrapy.Field()
    man_hinh = scrapy.Field()
    mat_kinh_man_hinh = scrapy.Field()
    ram = scrapy.Field()
    toc_do_cpu = scrapy.Field()
    so_nhan = scrapy.Field()
    chipset = scrapy.Field()
    gpu = scrapy.Field()
    cam_bien = scrapy.Field()
    the_nho_ngoai = scrapy.Field()
    dung_luong_the_nho_toi_da = scrapy.Field()
    dung_luong_danh_ba = scrapy.Field()
    rom = scrapy.Field()
    bo_nho_con_lai = scrapy.Field()
    kich_thuoc = scrapy.Field()
    trong_luong = scrapy.Field()
    kieu_dang = scrapy.Field()
    chat_lieu = scrapy.Field()
    chong_nuoc = scrapy.Field()
    loai_pin = scrapy.Field()
    dung_luong_pin = scrapy.Field()
    thao_roi_pin = scrapy.Field()
    thoi_gian_cho = scrapy.Field()
    thoi_gian_dam_thoai = scrapy.Field()
    thoi_gian_sac = scrapy.Field()
    sac_nhanh = scrapy.Field()
    ket_noi_usb = scrapy.Field()
    cong_ket_noi_khac = scrapy.Field()
    cong_sac = scrapy.Field()
    jack_in_out = scrapy.Field()
    wifi = scrapy.Field()
    gps = scrapy.Field()
    bluetooth = scrapy.Field()
    gprs = scrapy.Field()
    edge = scrapy.Field()
    loai_sim = scrapy.Field()
    mang_2g = scrapy.Field()
    mang_3g = scrapy.Field()
    mang_4g = scrapy.Field()
    khe_cam_sim = scrapy.Field()
    nfc = scrapy.Field()
    model_series = scrapy.Field()
    he_dieu_hanh = scrapy.Field()
    xem_phim = scrapy.Field()
    nghe_nhac = scrapy.Field()
    ghi_am = scrapy.Field()
    fm_radio = scrapy.Field()
    den_pin = scrapy.Field()
    chuc_nang_khac = scrapy.Field()
    thoi_gian_bao_hanh = scrapy.Field()
    xuat_xu = scrapy.Field()
    nam_san_xuat = scrapy.Field()
    do_phan_giai_cam_truoc = scrapy.Field()
    do_phan_giai_cam_sau = scrapy.Field()
    thong_tin_khac = scrapy.Field()
    quay_phim = scrapy.Field()
    den_flash = scrapy.Field()
    chup_anh_nang_cao = scrapy.Field()
    video_call = scrapy.Field()
    choi_game = scrapy.Field()
    box = scrapy.Field()
    ghi_chu = scrapy.Field()
    cong_nghe_pin = scrapy.Field()
    pass
